# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=halcyon
mod_name=Halcyon
mod_license=Models/Textures: All Rights Reserved | Music: CC BY-NC-SA | Code: MIT
mod_version=0.4.4+aria-of-the-moon
mod_group_id=EsetKalenko.Halcyon
mod_authors=Lead Devs: EsetKalenko (design), Fuzzy (music); Contributors: Cmdpro (programming/shaders/lore), DavidRarria09 (music), K King (sound), Multyfora (programming), Qther (node network improvements), TheRobbie73 (Sable compat)
mod_description=A story of reconciliation, told through a magitech mod about exploration and factory-building.

# Dependencies
databank_version=1.3.2
emi_version=1.1.24+1.21.1

# Integration Dependencies
mekanism_version=1.21.1-10.7.9.72
pastel_version=1.2.0
sable_version=1.2.2
sable_companion_version=1.6.0
malum_version=1.8.2
lodestone_version=1.8.2

# Integration Toggles
mekanism_enabled=true
pastel_enabled=true
sable_enabled=false
malum_enabled=true